### ISSUE TITLE
Original linear scalarization 

### ISSUE THREAD

**Issue by MarcuXu** [yobibyte/unitary-scalarization-dmtl#3]
Thank you for sharing your codes! Could you please tell me how to set the original linear scalarization in your codes since you use _Unitary Scalarization_ in your baselines.py? I appreciate your time and help!

**Comment by alessandrodepalma** [comment]
Thanks for your interest in our work! 
If your question is about setting non-unitary scalarization weights, this can be done by passing to the Baseline class a list of scalars for the weights (one per task): https://github.com/yobibyte/unitary-scalarization-dmtl/blob/main/optimizers/baselines.py#L7

**Comment by MarcuXu** [comment]
Thank you so much for your reply! I have achieved passing 2 random weights using
`r = np.random.rand(1)[0]
init_weights = np.array([r, 1-r])`
in multi-mnist dataset and it works! But for the celea and cityspaces, should I pass to the Baseline class a list of scalars for the weights based on the task number, like 40 for celea and 2 for cityspaces?

**Comment by alessandrodepalma** [comment]
That's correct: you need to provide as many scalars as the number of tasks (so, indeed, 40 for CelebA, and 2 for Cityscapes).

**Comment by MarcuXu** [comment]
Thank you for responding! Your work is fantastic and beneficial for new learners. I'm thrilled to use your code to study FL!

**Comment by MarcuXu** [comment]
The question is well answered by the authors! Thank you so much!
